"""create image log tables

Revision ID: 8e2f95869469
Revises: 
Create Date: 2025-05-17 11:47:53.573346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e2f95869469'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generationrequest',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lora', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('negative_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inference_steps', sa.Integer(), nullable=True),
    sa.Column('guidance_scale', sa.Float(), nullable=True),
    sa.Column('clip_skip', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('filter_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_image_s3_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_image_s3_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mask_s3_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mask_s3_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generationrequest_generation_type'), 'generationrequest', ['generation_type'], unique=False)
    op.create_index(op.f('ix_generationrequest_sub_type'), 'generationrequest', ['sub_type'], unique=False)
    op.create_table('generatedimage',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('s3_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['generationrequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generatedimage')
    op.drop_index(op.f('ix_generationrequest_sub_type'), table_name='generationrequest')
    op.drop_index(op.f('ix_generationrequest_generation_type'), table_name='generationrequest')
    op.drop_table('generationrequest')
    # ### end Alembic commands ###
